export const plataforms: string[] = [
    "Nintendo Switch",
    "Nintendo Wii u",
    "Nintendo Wii",
    "Nintendo Gamecube",
    "Nintendo 64",
    "Super Nintendo",
    "Nintendinho",
    "Playstation 5",
    "Playstation 4",
    "Playstation 3",
    "Playstation 2",
    "Playstation 1",
    "Xbox",
    "Xbox 360",
    "Xbox One",
    "Xbox Series X",
    "PC",
    "Dreamcast",
    "Sega Saturn",
    "32X",
    "Mega drive",
    "Master System",
]