import Header from '@/components/Header'
import './globals.css'
import type { Metadata } from 'next'
import { Inter, Palette_Mosaic } from 'next/font/google'
import localFont from "next/font/local"

const nico = localFont({
  src: "../../public/nicoMoji.ttf",
  variable: "--font-text",
})
const inter = Inter({ subsets: ['latin'] })
const palette = Palette_Mosaic({
  subsets: ["latin"],
  variable: "--font-title",
  weight: '400'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${palette.variable} ${nico.variable} font-sans`}>
        <div className='px-40 pt-20 flex flex-col items-center bg-black gap-10 min-h-screen'>
          <Header />
          {children}

        </div>
      </body>
    </html>
  )
}
